version: '3.8'

services:
  proxy-checker-express:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    container_name: proxy-checker-express
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules