version: '3.8'

services:
  proxy_checker_express:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    container_name: proxy_checker_express
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules